export const BASE_DIE_SIZE = 100;
export const DIE_SCALE = 0.75;
export const DIE_SIZE = BASE_DIE_SIZE * DIE_SCALE;

export const DICE_SPACING_RATIO = 0.24;
export const DICE_SPACING = DIE_SIZE * DICE_SPACING_RATIO;
export const DICE_SPACING_BASE = BASE_DIE_SIZE * DICE_SPACING_RATIO;

export const SCORE_DIE_RATIO = 0.38;
export const SCORE_DIE_SIZE = DIE_SIZE * SCORE_DIE_RATIO;
export const SCORE_DIE_BASE_SIZE = BASE_DIE_SIZE * SCORE_DIE_RATIO;

export const SMALL_SCORE_DIE_RATIO = 0.3;
export const SMALL_SCORE_DIE_SIZE = DIE_SIZE * SMALL_SCORE_DIE_RATIO;
export const SMALL_SCORE_DIE_BASE_SIZE = BASE_DIE_SIZE * SMALL_SCORE_DIE_RATIO;
